# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CocosSharp
description: > # this means to ignore newlines until "baseurl:"
  CocosSharp is a easy to use cross-platform games and visualisation library for C# and F#. 
  It is a .NET port of the popular Cocos2D engine and is powered by MonoGame.
baseurl: "/CocosSharp" # the subpath of your site, e.g. /blog
url: "http://mono.github.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown